project:
  type: website

website:
  title: "Trabajo Práctico Integral - Simulación en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "Reporte en PDF"
        href: "tpi-simulation-in-data-science.pdf" 


format:
  html:
    mainfont: "Noto Sans"       # Fuente del texto
    monofont: "Noto Sans Mono"  # Fuente para bloques de código
    css: styles.css
    toc: true
  pdf:
    documentclass: article
    pdf-engine: xelatex         
    mainfont: "Noto Sans"       # Nombre exacto de la fuente en tu PC
    monofont: "Noto Sans Mono"  # Fuente código (opcional)
    geometry:
      - top=1.5cm
      - bottom=1.5cm
      - left=1.5cm
      - right=1.5cm
    papersize: a4 # Es buena práctica definir el tamaño de hoja


