# _quarto.yml
project:
  type: website

execute:
  python: "C:\\Users\\Jenic\\AppData\\Local\\Programs\\Python\\Python312\\python.exe"

website:
  title: "Trabajo Práctico Integral - Simulación en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/georgsmeinung/tpi-simulacion
        text: "Código Fuente"      

format:
  html:
    mainfont: "Arial"
    monofont: "Consolas"
    toc: true
  pdf:
    pdf-engine: xelatex
    linestretch: 1.15
    documentclass: scrartcl
    indent: true # Use indentation for paragraphs, as is standard for APA
    fontsize: 10pt # Common APA font size
    geometry:
      - left=1in
      - top=1in
      - right=1in
      - bottom=1in         
    mainfont: "Arial"
    sansfont: "Arial"
    monofont: "Consolas"
    mathfont: "Cambria Math" # Optional, but recommended for math 
    papersize: a4 