project:
  type: website

website:
  title: "Trabajo Práctico Integral - Simulación en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/georgsmeinung/tpi-simulacion/blob/main/tpi-simulation-in-data-science.ipynb
        text: "Código Fuente"      

format:
  html:
    mainfont: "Arial"     # Fuente del texto
    monofont: "Consolas"  # Fuente para bloques de código
    css: styles.css
    toc: true
  pdf:
    linestretch: 1.5
    documentclass: scrartcl
    classoption:
      - onehalfspacing # Ensures 1.5 spacing is applied throughout the document
    indent: true # Use indentation for paragraphs, as is standard for APA
    fontsize: 12pt # Common APA font size
    geometry:
      - margin=1in
    pdf-engine: xelatex         
    mainfont: "Arial"       # Nombre exacto de la fuente en tu PC
    monofont: "Consolas"    # Fuente código (opcional)
    papersize: a4 
