project:
  type: website

website:
  title: "Trabajo Pr치ctico Integral - Simulaci칩n en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    mainfont: "Noto Sans"       # Fuente del texto
    monofont: "Noto Sans Mono"  # Fuente para bloques de c칩digo
    css: styles.css
    toc: true
  pdf:
    documentclass: article
    pdf-engine: xelatex         
    mainfont: "Arial"       # Nombre exacto de la fuente en tu PC
    monofont: "Consolas"    # Fuente c칩digo (opcional)
    geometry:
      - top=2.54cm
      - bottom=2.54cm
      - left=2.54cm
      - right=1.27cm
    papersize: a4 


