project:
  type: website

website:
  title: "Trabajo Pr치ctico Integral - Simulaci칩n en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/georgsmeinung/tpi-simulacion/blob/main/tpi-simulation-in-data-science.ipynb
        text: "C칩digo Fuente"      

format:
  html:
    mainfont: "Arial"     # Fuente del texto
    monofont: "Consolas"  # Fuente para bloques de c칩digo
    css: styles.css
    toc: true
  pdf:
    linestretch: 1.15
    documentclass: scrartcl
    indent: true # Use indentation for paragraphs, as is standard for APA
    fontsize: 10pt # Common APA font size
    geometry:
      - left=1in
      - top=1in
      - right=1in
      - bottom=1in
    pdf-engine: xelatex         
    mainfont: "Arial"
    sansfont: "Arial"
    monofont: "JetBrains Mono NL"
    mathfont: "Cambria Math" # Optional, but recommended for math 
    papersize: a4 