project:
  type: website

website:
  title: "Trabajo Práctico Integral - Simulación en Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/georgsmeinung/tpi-simulacion/blob/main/tpi-simulation-in-data-science.ipynb
        text: "Código Fuente"      

format:
  html:
    mainfont: "Noto Sans"       # Fuente del texto
    monofont: "Noto Sans Mono"  # Fuente para bloques de código
    css: styles.css
    toc: true
  pdf:
    documentclass: article
    pdf-engine: xelatex         
    mainfont: "Arial"       # Nombre exacto de la fuente en tu PC
    monofont: "Consolas"    # Fuente código (opcional)
    geometry:
      - top=2.54cm
      - bottom=2.54cm
      - left=2.54cm
      - right=1.27cm
    papersize: a4 


